name: Run on runner

on:
  workflow_dispatch

jobs:
  process-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
  
      - name: install deps Download, extract, and build kernel
        run: |
         sudo apt install build-essential gcc-arm-linux-gnueabi gcc-aarch64-linux-gnu  ccache  python-is-python3 libarchive-tools \
         android-sdk-libsparse-utils device-tree-compiler libncurses-dev wget clang
         bash run.sh
        

      - name: Create a new GitHub release and tag
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: "Release kernel"
          body: "This release includes the latest build  kernel."
          files: |
            out/arch/arm64/boot/Image.gz
            kernel.tar.gz
          
            
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
